/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.types.Request');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.types.RequestBeginBlock');
goog.require('proto.types.RequestCheckTx');
goog.require('proto.types.RequestCommit');
goog.require('proto.types.RequestDeliverTx');
goog.require('proto.types.RequestEcho');
goog.require('proto.types.RequestEndBlock');
goog.require('proto.types.RequestFlush');
goog.require('proto.types.RequestInfo');
goog.require('proto.types.RequestInitChain');
goog.require('proto.types.RequestQuery');
goog.require('proto.types.RequestSetOption');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.types.Request = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.types.Request.oneofGroups_);
};
goog.inherits(proto.types.Request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.types.Request.displayName = 'proto.types.Request';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.types.Request.oneofGroups_ = [[2,3,4,5,6,7,8,9,19,11,12]];

/**
 * @enum {number}
 */
proto.types.Request.ValueCase = {
  VALUE_NOT_SET: 0,
  ECHO: 2,
  FLUSH: 3,
  INFO: 4,
  SET_OPTION: 5,
  INIT_CHAIN: 6,
  QUERY: 7,
  BEGIN_BLOCK: 8,
  CHECK_TX: 9,
  DELIVER_TX: 19,
  END_BLOCK: 11,
  COMMIT: 12
};

/**
 * @return {proto.types.Request.ValueCase}
 */
proto.types.Request.prototype.getValueCase = function() {
  return /** @type {proto.types.Request.ValueCase} */(jspb.Message.computeOneofCase(this, proto.types.Request.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.types.Request.prototype.toObject = function(opt_includeInstance) {
  return proto.types.Request.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.types.Request} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.Request.toObject = function(includeInstance, msg) {
  var f, obj = {
    echo: (f = msg.getEcho()) && proto.types.RequestEcho.toObject(includeInstance, f),
    flush: (f = msg.getFlush()) && proto.types.RequestFlush.toObject(includeInstance, f),
    info: (f = msg.getInfo()) && proto.types.RequestInfo.toObject(includeInstance, f),
    setOption: (f = msg.getSetOption()) && proto.types.RequestSetOption.toObject(includeInstance, f),
    initChain: (f = msg.getInitChain()) && proto.types.RequestInitChain.toObject(includeInstance, f),
    query: (f = msg.getQuery()) && proto.types.RequestQuery.toObject(includeInstance, f),
    beginBlock: (f = msg.getBeginBlock()) && proto.types.RequestBeginBlock.toObject(includeInstance, f),
    checkTx: (f = msg.getCheckTx()) && proto.types.RequestCheckTx.toObject(includeInstance, f),
    deliverTx: (f = msg.getDeliverTx()) && proto.types.RequestDeliverTx.toObject(includeInstance, f),
    endBlock: (f = msg.getEndBlock()) && proto.types.RequestEndBlock.toObject(includeInstance, f),
    commit: (f = msg.getCommit()) && proto.types.RequestCommit.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.types.Request}
 */
proto.types.Request.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.types.Request;
  return proto.types.Request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.types.Request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.types.Request}
 */
proto.types.Request.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new proto.types.RequestEcho;
      reader.readMessage(value,proto.types.RequestEcho.deserializeBinaryFromReader);
      msg.setEcho(value);
      break;
    case 3:
      var value = new proto.types.RequestFlush;
      reader.readMessage(value,proto.types.RequestFlush.deserializeBinaryFromReader);
      msg.setFlush(value);
      break;
    case 4:
      var value = new proto.types.RequestInfo;
      reader.readMessage(value,proto.types.RequestInfo.deserializeBinaryFromReader);
      msg.setInfo(value);
      break;
    case 5:
      var value = new proto.types.RequestSetOption;
      reader.readMessage(value,proto.types.RequestSetOption.deserializeBinaryFromReader);
      msg.setSetOption(value);
      break;
    case 6:
      var value = new proto.types.RequestInitChain;
      reader.readMessage(value,proto.types.RequestInitChain.deserializeBinaryFromReader);
      msg.setInitChain(value);
      break;
    case 7:
      var value = new proto.types.RequestQuery;
      reader.readMessage(value,proto.types.RequestQuery.deserializeBinaryFromReader);
      msg.setQuery(value);
      break;
    case 8:
      var value = new proto.types.RequestBeginBlock;
      reader.readMessage(value,proto.types.RequestBeginBlock.deserializeBinaryFromReader);
      msg.setBeginBlock(value);
      break;
    case 9:
      var value = new proto.types.RequestCheckTx;
      reader.readMessage(value,proto.types.RequestCheckTx.deserializeBinaryFromReader);
      msg.setCheckTx(value);
      break;
    case 19:
      var value = new proto.types.RequestDeliverTx;
      reader.readMessage(value,proto.types.RequestDeliverTx.deserializeBinaryFromReader);
      msg.setDeliverTx(value);
      break;
    case 11:
      var value = new proto.types.RequestEndBlock;
      reader.readMessage(value,proto.types.RequestEndBlock.deserializeBinaryFromReader);
      msg.setEndBlock(value);
      break;
    case 12:
      var value = new proto.types.RequestCommit;
      reader.readMessage(value,proto.types.RequestCommit.deserializeBinaryFromReader);
      msg.setCommit(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.types.Request.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.types.Request.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.types.Request} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.Request.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEcho();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.types.RequestEcho.serializeBinaryToWriter
    );
  }
  f = message.getFlush();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.types.RequestFlush.serializeBinaryToWriter
    );
  }
  f = message.getInfo();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.types.RequestInfo.serializeBinaryToWriter
    );
  }
  f = message.getSetOption();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.types.RequestSetOption.serializeBinaryToWriter
    );
  }
  f = message.getInitChain();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.types.RequestInitChain.serializeBinaryToWriter
    );
  }
  f = message.getQuery();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.types.RequestQuery.serializeBinaryToWriter
    );
  }
  f = message.getBeginBlock();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.types.RequestBeginBlock.serializeBinaryToWriter
    );
  }
  f = message.getCheckTx();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.types.RequestCheckTx.serializeBinaryToWriter
    );
  }
  f = message.getDeliverTx();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      proto.types.RequestDeliverTx.serializeBinaryToWriter
    );
  }
  f = message.getEndBlock();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.types.RequestEndBlock.serializeBinaryToWriter
    );
  }
  f = message.getCommit();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.types.RequestCommit.serializeBinaryToWriter
    );
  }
};


/**
 * optional RequestEcho echo = 2;
 * @return {?proto.types.RequestEcho}
 */
proto.types.Request.prototype.getEcho = function() {
  return /** @type{?proto.types.RequestEcho} */ (
    jspb.Message.getWrapperField(this, proto.types.RequestEcho, 2));
};


/** @param {?proto.types.RequestEcho|undefined} value */
proto.types.Request.prototype.setEcho = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.types.Request.oneofGroups_[0], value);
};


proto.types.Request.prototype.clearEcho = function() {
  this.setEcho(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Request.prototype.hasEcho = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional RequestFlush flush = 3;
 * @return {?proto.types.RequestFlush}
 */
proto.types.Request.prototype.getFlush = function() {
  return /** @type{?proto.types.RequestFlush} */ (
    jspb.Message.getWrapperField(this, proto.types.RequestFlush, 3));
};


/** @param {?proto.types.RequestFlush|undefined} value */
proto.types.Request.prototype.setFlush = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.types.Request.oneofGroups_[0], value);
};


proto.types.Request.prototype.clearFlush = function() {
  this.setFlush(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Request.prototype.hasFlush = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional RequestInfo info = 4;
 * @return {?proto.types.RequestInfo}
 */
proto.types.Request.prototype.getInfo = function() {
  return /** @type{?proto.types.RequestInfo} */ (
    jspb.Message.getWrapperField(this, proto.types.RequestInfo, 4));
};


/** @param {?proto.types.RequestInfo|undefined} value */
proto.types.Request.prototype.setInfo = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.types.Request.oneofGroups_[0], value);
};


proto.types.Request.prototype.clearInfo = function() {
  this.setInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Request.prototype.hasInfo = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional RequestSetOption set_option = 5;
 * @return {?proto.types.RequestSetOption}
 */
proto.types.Request.prototype.getSetOption = function() {
  return /** @type{?proto.types.RequestSetOption} */ (
    jspb.Message.getWrapperField(this, proto.types.RequestSetOption, 5));
};


/** @param {?proto.types.RequestSetOption|undefined} value */
proto.types.Request.prototype.setSetOption = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.types.Request.oneofGroups_[0], value);
};


proto.types.Request.prototype.clearSetOption = function() {
  this.setSetOption(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Request.prototype.hasSetOption = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional RequestInitChain init_chain = 6;
 * @return {?proto.types.RequestInitChain}
 */
proto.types.Request.prototype.getInitChain = function() {
  return /** @type{?proto.types.RequestInitChain} */ (
    jspb.Message.getWrapperField(this, proto.types.RequestInitChain, 6));
};


/** @param {?proto.types.RequestInitChain|undefined} value */
proto.types.Request.prototype.setInitChain = function(value) {
  jspb.Message.setOneofWrapperField(this, 6, proto.types.Request.oneofGroups_[0], value);
};


proto.types.Request.prototype.clearInitChain = function() {
  this.setInitChain(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Request.prototype.hasInitChain = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional RequestQuery query = 7;
 * @return {?proto.types.RequestQuery}
 */
proto.types.Request.prototype.getQuery = function() {
  return /** @type{?proto.types.RequestQuery} */ (
    jspb.Message.getWrapperField(this, proto.types.RequestQuery, 7));
};


/** @param {?proto.types.RequestQuery|undefined} value */
proto.types.Request.prototype.setQuery = function(value) {
  jspb.Message.setOneofWrapperField(this, 7, proto.types.Request.oneofGroups_[0], value);
};


proto.types.Request.prototype.clearQuery = function() {
  this.setQuery(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Request.prototype.hasQuery = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional RequestBeginBlock begin_block = 8;
 * @return {?proto.types.RequestBeginBlock}
 */
proto.types.Request.prototype.getBeginBlock = function() {
  return /** @type{?proto.types.RequestBeginBlock} */ (
    jspb.Message.getWrapperField(this, proto.types.RequestBeginBlock, 8));
};


/** @param {?proto.types.RequestBeginBlock|undefined} value */
proto.types.Request.prototype.setBeginBlock = function(value) {
  jspb.Message.setOneofWrapperField(this, 8, proto.types.Request.oneofGroups_[0], value);
};


proto.types.Request.prototype.clearBeginBlock = function() {
  this.setBeginBlock(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Request.prototype.hasBeginBlock = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional RequestCheckTx check_tx = 9;
 * @return {?proto.types.RequestCheckTx}
 */
proto.types.Request.prototype.getCheckTx = function() {
  return /** @type{?proto.types.RequestCheckTx} */ (
    jspb.Message.getWrapperField(this, proto.types.RequestCheckTx, 9));
};


/** @param {?proto.types.RequestCheckTx|undefined} value */
proto.types.Request.prototype.setCheckTx = function(value) {
  jspb.Message.setOneofWrapperField(this, 9, proto.types.Request.oneofGroups_[0], value);
};


proto.types.Request.prototype.clearCheckTx = function() {
  this.setCheckTx(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Request.prototype.hasCheckTx = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional RequestDeliverTx deliver_tx = 19;
 * @return {?proto.types.RequestDeliverTx}
 */
proto.types.Request.prototype.getDeliverTx = function() {
  return /** @type{?proto.types.RequestDeliverTx} */ (
    jspb.Message.getWrapperField(this, proto.types.RequestDeliverTx, 19));
};


/** @param {?proto.types.RequestDeliverTx|undefined} value */
proto.types.Request.prototype.setDeliverTx = function(value) {
  jspb.Message.setOneofWrapperField(this, 19, proto.types.Request.oneofGroups_[0], value);
};


proto.types.Request.prototype.clearDeliverTx = function() {
  this.setDeliverTx(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Request.prototype.hasDeliverTx = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional RequestEndBlock end_block = 11;
 * @return {?proto.types.RequestEndBlock}
 */
proto.types.Request.prototype.getEndBlock = function() {
  return /** @type{?proto.types.RequestEndBlock} */ (
    jspb.Message.getWrapperField(this, proto.types.RequestEndBlock, 11));
};


/** @param {?proto.types.RequestEndBlock|undefined} value */
proto.types.Request.prototype.setEndBlock = function(value) {
  jspb.Message.setOneofWrapperField(this, 11, proto.types.Request.oneofGroups_[0], value);
};


proto.types.Request.prototype.clearEndBlock = function() {
  this.setEndBlock(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Request.prototype.hasEndBlock = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional RequestCommit commit = 12;
 * @return {?proto.types.RequestCommit}
 */
proto.types.Request.prototype.getCommit = function() {
  return /** @type{?proto.types.RequestCommit} */ (
    jspb.Message.getWrapperField(this, proto.types.RequestCommit, 12));
};


/** @param {?proto.types.RequestCommit|undefined} value */
proto.types.Request.prototype.setCommit = function(value) {
  jspb.Message.setOneofWrapperField(this, 12, proto.types.Request.oneofGroups_[0], value);
};


proto.types.Request.prototype.clearCommit = function() {
  this.setCommit(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Request.prototype.hasCommit = function() {
  return jspb.Message.getField(this, 12) != null;
};


