/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.types.Response');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.types.ResponseBeginBlock');
goog.require('proto.types.ResponseCheckTx');
goog.require('proto.types.ResponseCommit');
goog.require('proto.types.ResponseDeliverTx');
goog.require('proto.types.ResponseEcho');
goog.require('proto.types.ResponseEndBlock');
goog.require('proto.types.ResponseException');
goog.require('proto.types.ResponseFlush');
goog.require('proto.types.ResponseInfo');
goog.require('proto.types.ResponseInitChain');
goog.require('proto.types.ResponseQuery');
goog.require('proto.types.ResponseSetOption');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.types.Response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.types.Response.oneofGroups_);
};
goog.inherits(proto.types.Response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.types.Response.displayName = 'proto.types.Response';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.types.Response.oneofGroups_ = [[1,2,3,4,5,6,7,8,9,10,11,12]];

/**
 * @enum {number}
 */
proto.types.Response.ValueCase = {
  VALUE_NOT_SET: 0,
  EXCEPTION: 1,
  ECHO: 2,
  FLUSH: 3,
  INFO: 4,
  SET_OPTION: 5,
  INIT_CHAIN: 6,
  QUERY: 7,
  BEGIN_BLOCK: 8,
  CHECK_TX: 9,
  DELIVER_TX: 10,
  END_BLOCK: 11,
  COMMIT: 12
};

/**
 * @return {proto.types.Response.ValueCase}
 */
proto.types.Response.prototype.getValueCase = function() {
  return /** @type {proto.types.Response.ValueCase} */(jspb.Message.computeOneofCase(this, proto.types.Response.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.types.Response.prototype.toObject = function(opt_includeInstance) {
  return proto.types.Response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.types.Response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.Response.toObject = function(includeInstance, msg) {
  var f, obj = {
    exception: (f = msg.getException()) && proto.types.ResponseException.toObject(includeInstance, f),
    echo: (f = msg.getEcho()) && proto.types.ResponseEcho.toObject(includeInstance, f),
    flush: (f = msg.getFlush()) && proto.types.ResponseFlush.toObject(includeInstance, f),
    info: (f = msg.getInfo()) && proto.types.ResponseInfo.toObject(includeInstance, f),
    setOption: (f = msg.getSetOption()) && proto.types.ResponseSetOption.toObject(includeInstance, f),
    initChain: (f = msg.getInitChain()) && proto.types.ResponseInitChain.toObject(includeInstance, f),
    query: (f = msg.getQuery()) && proto.types.ResponseQuery.toObject(includeInstance, f),
    beginBlock: (f = msg.getBeginBlock()) && proto.types.ResponseBeginBlock.toObject(includeInstance, f),
    checkTx: (f = msg.getCheckTx()) && proto.types.ResponseCheckTx.toObject(includeInstance, f),
    deliverTx: (f = msg.getDeliverTx()) && proto.types.ResponseDeliverTx.toObject(includeInstance, f),
    endBlock: (f = msg.getEndBlock()) && proto.types.ResponseEndBlock.toObject(includeInstance, f),
    commit: (f = msg.getCommit()) && proto.types.ResponseCommit.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.types.Response}
 */
proto.types.Response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.types.Response;
  return proto.types.Response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.types.Response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.types.Response}
 */
proto.types.Response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.types.ResponseException;
      reader.readMessage(value,proto.types.ResponseException.deserializeBinaryFromReader);
      msg.setException(value);
      break;
    case 2:
      var value = new proto.types.ResponseEcho;
      reader.readMessage(value,proto.types.ResponseEcho.deserializeBinaryFromReader);
      msg.setEcho(value);
      break;
    case 3:
      var value = new proto.types.ResponseFlush;
      reader.readMessage(value,proto.types.ResponseFlush.deserializeBinaryFromReader);
      msg.setFlush(value);
      break;
    case 4:
      var value = new proto.types.ResponseInfo;
      reader.readMessage(value,proto.types.ResponseInfo.deserializeBinaryFromReader);
      msg.setInfo(value);
      break;
    case 5:
      var value = new proto.types.ResponseSetOption;
      reader.readMessage(value,proto.types.ResponseSetOption.deserializeBinaryFromReader);
      msg.setSetOption(value);
      break;
    case 6:
      var value = new proto.types.ResponseInitChain;
      reader.readMessage(value,proto.types.ResponseInitChain.deserializeBinaryFromReader);
      msg.setInitChain(value);
      break;
    case 7:
      var value = new proto.types.ResponseQuery;
      reader.readMessage(value,proto.types.ResponseQuery.deserializeBinaryFromReader);
      msg.setQuery(value);
      break;
    case 8:
      var value = new proto.types.ResponseBeginBlock;
      reader.readMessage(value,proto.types.ResponseBeginBlock.deserializeBinaryFromReader);
      msg.setBeginBlock(value);
      break;
    case 9:
      var value = new proto.types.ResponseCheckTx;
      reader.readMessage(value,proto.types.ResponseCheckTx.deserializeBinaryFromReader);
      msg.setCheckTx(value);
      break;
    case 10:
      var value = new proto.types.ResponseDeliverTx;
      reader.readMessage(value,proto.types.ResponseDeliverTx.deserializeBinaryFromReader);
      msg.setDeliverTx(value);
      break;
    case 11:
      var value = new proto.types.ResponseEndBlock;
      reader.readMessage(value,proto.types.ResponseEndBlock.deserializeBinaryFromReader);
      msg.setEndBlock(value);
      break;
    case 12:
      var value = new proto.types.ResponseCommit;
      reader.readMessage(value,proto.types.ResponseCommit.deserializeBinaryFromReader);
      msg.setCommit(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.types.Response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.types.Response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.types.Response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.Response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getException();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.types.ResponseException.serializeBinaryToWriter
    );
  }
  f = message.getEcho();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.types.ResponseEcho.serializeBinaryToWriter
    );
  }
  f = message.getFlush();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.types.ResponseFlush.serializeBinaryToWriter
    );
  }
  f = message.getInfo();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.types.ResponseInfo.serializeBinaryToWriter
    );
  }
  f = message.getSetOption();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.types.ResponseSetOption.serializeBinaryToWriter
    );
  }
  f = message.getInitChain();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.types.ResponseInitChain.serializeBinaryToWriter
    );
  }
  f = message.getQuery();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.types.ResponseQuery.serializeBinaryToWriter
    );
  }
  f = message.getBeginBlock();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.types.ResponseBeginBlock.serializeBinaryToWriter
    );
  }
  f = message.getCheckTx();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.types.ResponseCheckTx.serializeBinaryToWriter
    );
  }
  f = message.getDeliverTx();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.types.ResponseDeliverTx.serializeBinaryToWriter
    );
  }
  f = message.getEndBlock();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.types.ResponseEndBlock.serializeBinaryToWriter
    );
  }
  f = message.getCommit();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.types.ResponseCommit.serializeBinaryToWriter
    );
  }
};


/**
 * optional ResponseException exception = 1;
 * @return {?proto.types.ResponseException}
 */
proto.types.Response.prototype.getException = function() {
  return /** @type{?proto.types.ResponseException} */ (
    jspb.Message.getWrapperField(this, proto.types.ResponseException, 1));
};


/** @param {?proto.types.ResponseException|undefined} value */
proto.types.Response.prototype.setException = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.types.Response.oneofGroups_[0], value);
};


proto.types.Response.prototype.clearException = function() {
  this.setException(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Response.prototype.hasException = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ResponseEcho echo = 2;
 * @return {?proto.types.ResponseEcho}
 */
proto.types.Response.prototype.getEcho = function() {
  return /** @type{?proto.types.ResponseEcho} */ (
    jspb.Message.getWrapperField(this, proto.types.ResponseEcho, 2));
};


/** @param {?proto.types.ResponseEcho|undefined} value */
proto.types.Response.prototype.setEcho = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.types.Response.oneofGroups_[0], value);
};


proto.types.Response.prototype.clearEcho = function() {
  this.setEcho(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Response.prototype.hasEcho = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ResponseFlush flush = 3;
 * @return {?proto.types.ResponseFlush}
 */
proto.types.Response.prototype.getFlush = function() {
  return /** @type{?proto.types.ResponseFlush} */ (
    jspb.Message.getWrapperField(this, proto.types.ResponseFlush, 3));
};


/** @param {?proto.types.ResponseFlush|undefined} value */
proto.types.Response.prototype.setFlush = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.types.Response.oneofGroups_[0], value);
};


proto.types.Response.prototype.clearFlush = function() {
  this.setFlush(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Response.prototype.hasFlush = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ResponseInfo info = 4;
 * @return {?proto.types.ResponseInfo}
 */
proto.types.Response.prototype.getInfo = function() {
  return /** @type{?proto.types.ResponseInfo} */ (
    jspb.Message.getWrapperField(this, proto.types.ResponseInfo, 4));
};


/** @param {?proto.types.ResponseInfo|undefined} value */
proto.types.Response.prototype.setInfo = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.types.Response.oneofGroups_[0], value);
};


proto.types.Response.prototype.clearInfo = function() {
  this.setInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Response.prototype.hasInfo = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional ResponseSetOption set_option = 5;
 * @return {?proto.types.ResponseSetOption}
 */
proto.types.Response.prototype.getSetOption = function() {
  return /** @type{?proto.types.ResponseSetOption} */ (
    jspb.Message.getWrapperField(this, proto.types.ResponseSetOption, 5));
};


/** @param {?proto.types.ResponseSetOption|undefined} value */
proto.types.Response.prototype.setSetOption = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.types.Response.oneofGroups_[0], value);
};


proto.types.Response.prototype.clearSetOption = function() {
  this.setSetOption(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Response.prototype.hasSetOption = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional ResponseInitChain init_chain = 6;
 * @return {?proto.types.ResponseInitChain}
 */
proto.types.Response.prototype.getInitChain = function() {
  return /** @type{?proto.types.ResponseInitChain} */ (
    jspb.Message.getWrapperField(this, proto.types.ResponseInitChain, 6));
};


/** @param {?proto.types.ResponseInitChain|undefined} value */
proto.types.Response.prototype.setInitChain = function(value) {
  jspb.Message.setOneofWrapperField(this, 6, proto.types.Response.oneofGroups_[0], value);
};


proto.types.Response.prototype.clearInitChain = function() {
  this.setInitChain(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Response.prototype.hasInitChain = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional ResponseQuery query = 7;
 * @return {?proto.types.ResponseQuery}
 */
proto.types.Response.prototype.getQuery = function() {
  return /** @type{?proto.types.ResponseQuery} */ (
    jspb.Message.getWrapperField(this, proto.types.ResponseQuery, 7));
};


/** @param {?proto.types.ResponseQuery|undefined} value */
proto.types.Response.prototype.setQuery = function(value) {
  jspb.Message.setOneofWrapperField(this, 7, proto.types.Response.oneofGroups_[0], value);
};


proto.types.Response.prototype.clearQuery = function() {
  this.setQuery(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Response.prototype.hasQuery = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional ResponseBeginBlock begin_block = 8;
 * @return {?proto.types.ResponseBeginBlock}
 */
proto.types.Response.prototype.getBeginBlock = function() {
  return /** @type{?proto.types.ResponseBeginBlock} */ (
    jspb.Message.getWrapperField(this, proto.types.ResponseBeginBlock, 8));
};


/** @param {?proto.types.ResponseBeginBlock|undefined} value */
proto.types.Response.prototype.setBeginBlock = function(value) {
  jspb.Message.setOneofWrapperField(this, 8, proto.types.Response.oneofGroups_[0], value);
};


proto.types.Response.prototype.clearBeginBlock = function() {
  this.setBeginBlock(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Response.prototype.hasBeginBlock = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional ResponseCheckTx check_tx = 9;
 * @return {?proto.types.ResponseCheckTx}
 */
proto.types.Response.prototype.getCheckTx = function() {
  return /** @type{?proto.types.ResponseCheckTx} */ (
    jspb.Message.getWrapperField(this, proto.types.ResponseCheckTx, 9));
};


/** @param {?proto.types.ResponseCheckTx|undefined} value */
proto.types.Response.prototype.setCheckTx = function(value) {
  jspb.Message.setOneofWrapperField(this, 9, proto.types.Response.oneofGroups_[0], value);
};


proto.types.Response.prototype.clearCheckTx = function() {
  this.setCheckTx(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Response.prototype.hasCheckTx = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional ResponseDeliverTx deliver_tx = 10;
 * @return {?proto.types.ResponseDeliverTx}
 */
proto.types.Response.prototype.getDeliverTx = function() {
  return /** @type{?proto.types.ResponseDeliverTx} */ (
    jspb.Message.getWrapperField(this, proto.types.ResponseDeliverTx, 10));
};


/** @param {?proto.types.ResponseDeliverTx|undefined} value */
proto.types.Response.prototype.setDeliverTx = function(value) {
  jspb.Message.setOneofWrapperField(this, 10, proto.types.Response.oneofGroups_[0], value);
};


proto.types.Response.prototype.clearDeliverTx = function() {
  this.setDeliverTx(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Response.prototype.hasDeliverTx = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional ResponseEndBlock end_block = 11;
 * @return {?proto.types.ResponseEndBlock}
 */
proto.types.Response.prototype.getEndBlock = function() {
  return /** @type{?proto.types.ResponseEndBlock} */ (
    jspb.Message.getWrapperField(this, proto.types.ResponseEndBlock, 11));
};


/** @param {?proto.types.ResponseEndBlock|undefined} value */
proto.types.Response.prototype.setEndBlock = function(value) {
  jspb.Message.setOneofWrapperField(this, 11, proto.types.Response.oneofGroups_[0], value);
};


proto.types.Response.prototype.clearEndBlock = function() {
  this.setEndBlock(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Response.prototype.hasEndBlock = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional ResponseCommit commit = 12;
 * @return {?proto.types.ResponseCommit}
 */
proto.types.Response.prototype.getCommit = function() {
  return /** @type{?proto.types.ResponseCommit} */ (
    jspb.Message.getWrapperField(this, proto.types.ResponseCommit, 12));
};


/** @param {?proto.types.ResponseCommit|undefined} value */
proto.types.Response.prototype.setCommit = function(value) {
  jspb.Message.setOneofWrapperField(this, 12, proto.types.Response.oneofGroups_[0], value);
};


proto.types.Response.prototype.clearCommit = function() {
  this.setCommit(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.Response.prototype.hasCommit = function() {
  return jspb.Message.getField(this, 12) != null;
};


