/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.types.ResponseEndBlock');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.common.KVPair');
goog.require('proto.types.ConsensusParams');
goog.require('proto.types.ValidatorUpdate');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.types.ResponseEndBlock = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.types.ResponseEndBlock.repeatedFields_, null);
};
goog.inherits(proto.types.ResponseEndBlock, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.types.ResponseEndBlock.displayName = 'proto.types.ResponseEndBlock';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.types.ResponseEndBlock.repeatedFields_ = [1,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.types.ResponseEndBlock.prototype.toObject = function(opt_includeInstance) {
  return proto.types.ResponseEndBlock.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.types.ResponseEndBlock} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.ResponseEndBlock.toObject = function(includeInstance, msg) {
  var f, obj = {
    validatorUpdatesList: jspb.Message.toObjectList(msg.getValidatorUpdatesList(),
    proto.types.ValidatorUpdate.toObject, includeInstance),
    consensusParamUpdates: (f = msg.getConsensusParamUpdates()) && proto.types.ConsensusParams.toObject(includeInstance, f),
    tagsList: jspb.Message.toObjectList(msg.getTagsList(),
    proto.common.KVPair.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.types.ResponseEndBlock}
 */
proto.types.ResponseEndBlock.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.types.ResponseEndBlock;
  return proto.types.ResponseEndBlock.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.types.ResponseEndBlock} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.types.ResponseEndBlock}
 */
proto.types.ResponseEndBlock.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.types.ValidatorUpdate;
      reader.readMessage(value,proto.types.ValidatorUpdate.deserializeBinaryFromReader);
      msg.addValidatorUpdates(value);
      break;
    case 2:
      var value = new proto.types.ConsensusParams;
      reader.readMessage(value,proto.types.ConsensusParams.deserializeBinaryFromReader);
      msg.setConsensusParamUpdates(value);
      break;
    case 3:
      var value = new proto.common.KVPair;
      reader.readMessage(value,proto.common.KVPair.deserializeBinaryFromReader);
      msg.addTags(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.types.ResponseEndBlock.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.types.ResponseEndBlock.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.types.ResponseEndBlock} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.types.ResponseEndBlock.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValidatorUpdatesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.types.ValidatorUpdate.serializeBinaryToWriter
    );
  }
  f = message.getConsensusParamUpdates();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.types.ConsensusParams.serializeBinaryToWriter
    );
  }
  f = message.getTagsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.common.KVPair.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ValidatorUpdate validator_updates = 1;
 * @return {!Array<!proto.types.ValidatorUpdate>}
 */
proto.types.ResponseEndBlock.prototype.getValidatorUpdatesList = function() {
  return /** @type{!Array<!proto.types.ValidatorUpdate>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.types.ValidatorUpdate, 1));
};


/** @param {!Array<!proto.types.ValidatorUpdate>} value */
proto.types.ResponseEndBlock.prototype.setValidatorUpdatesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.types.ValidatorUpdate=} opt_value
 * @param {number=} opt_index
 * @return {!proto.types.ValidatorUpdate}
 */
proto.types.ResponseEndBlock.prototype.addValidatorUpdates = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.types.ValidatorUpdate, opt_index);
};


proto.types.ResponseEndBlock.prototype.clearValidatorUpdatesList = function() {
  this.setValidatorUpdatesList([]);
};


/**
 * optional ConsensusParams consensus_param_updates = 2;
 * @return {?proto.types.ConsensusParams}
 */
proto.types.ResponseEndBlock.prototype.getConsensusParamUpdates = function() {
  return /** @type{?proto.types.ConsensusParams} */ (
    jspb.Message.getWrapperField(this, proto.types.ConsensusParams, 2));
};


/** @param {?proto.types.ConsensusParams|undefined} value */
proto.types.ResponseEndBlock.prototype.setConsensusParamUpdates = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.types.ResponseEndBlock.prototype.clearConsensusParamUpdates = function() {
  this.setConsensusParamUpdates(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.types.ResponseEndBlock.prototype.hasConsensusParamUpdates = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated common.KVPair tags = 3;
 * @return {!Array<!proto.common.KVPair>}
 */
proto.types.ResponseEndBlock.prototype.getTagsList = function() {
  return /** @type{!Array<!proto.common.KVPair>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.common.KVPair, 3));
};


/** @param {!Array<!proto.common.KVPair>} value */
proto.types.ResponseEndBlock.prototype.setTagsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.common.KVPair=} opt_value
 * @param {number=} opt_index
 * @return {!proto.common.KVPair}
 */
proto.types.ResponseEndBlock.prototype.addTags = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.common.KVPair, opt_index);
};


proto.types.ResponseEndBlock.prototype.clearTagsList = function() {
  this.setTagsList([]);
};


